language: node_js

sudo: false

node_js:
  - "node"

cache: yarn

jobs:
  include:
    - stage: "Build"
      install:
        - yarn install
        - yarn run vscode:prepublish
      script: yarn run vscode:package
